import './bootstrap';
import PrimeVue from 'primevue/config';
import 'primevue/resources/themes/lara-light-blue/theme.css';
import 'primevue/resources/primevue.min.css';
import 'primeicons/primeicons.css';
import { createApp, h } from 'vue';
import { createInertiaApp } from '@inertiajs/vue3';
import { resolvePageComponent } from 'laravel-vite-plugin/inertia-helpers';

createInertiaApp({
    resolve: (name) =>
        resolvePageComponent(
            `./Pages/${name}.vue`,
            import.meta.glob('./Pages/**/*.vue')
        ),
    setup({ el, App, props, plugin }) {
        createApp({ render: () => h(App, props) })
            .use(plugin)
            .use(PrimeVue, {
                locale: {
                    startsWith: 'Начинается с',
                    contains: 'Содержит',
                    notContains: 'Не содержит',
                    endsWith: 'Заканчивается на',
                    equals: 'Равно',
                    notEquals: 'Не равно',
                    noFilter: 'Без фильтра',
                    lt: 'Меньше',
                    lte: 'Меньше или равно',
                    gt: 'Больше',
                    gte: 'Больше или равно',
                    dateIs: 'Дата равна',
                    dateIsNot: 'Дата не равна',
                    dateBefore: 'Дата до',
                    dateAfter: 'Дата после',
                    clear: 'Очистить',
                    apply: 'Применить',
                    matchAll: 'Совпадают все',
                    matchAny: 'Совпадает хотя бы одно',
                    addRule: 'Добавить правило',
                    removeRule: 'Удалить правило',
                    accept: 'Да',
                    reject: 'Нет',
                    choose: 'Выбрать',
                    upload: 'Загрузить',
                    cancel: 'Отмена',
                    completed: 'Готово',
                    pending: 'В ожидании',
                    dayNames: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
                    dayNamesShort: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
                    dayNamesMin: ['Вс', 'Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб'],
                    monthNames: [
                        'Январь',
                        'Февраль',
                        'Март',
                        'Апрель',
                        'Май',
                        'Июнь',
                        'Июль',
                        'Август',
                        'Сентябрь',
                        'Октябрь',
                        'Ноябрь',
                        'Декабрь',
                    ],
                    monthNamesShort: [
                        'Янв',
                        'Фев',
                        'Мар',
                        'Апр',
                        'Май',
                        'Июн',
                        'Июл',
                        'Авг',
                        'Сен',
                        'Окт',
                        'Ноя',
                        'Дек',
                    ],
                    chooseDate: 'Выберите дату',
                    chooseTime: 'Выберите время',
                    chooseMonth: 'Выберите месяц',
                    chooseYear: 'Выберите год',
                    today: 'Сегодня',
                    weekHeader: 'Нед',
                    firstDayOfWeek: 1,
                    dateFormat: 'dd.mm.yy',
                    weak: 'Слабый',
                    medium: 'Средний',
                    strong: 'Сильный',
                    passwordPrompt: 'Введите пароль',
                    emptyFilterMessage: 'Нет результатов',
                    emptyMessage: 'Нет доступных вариантов',
                    aria: {
                        trueLabel: 'Да',
                        falseLabel: 'Нет',
                        nullLabel: 'Не выбрано',
                        star: '1 звезда',
                        stars: '{star} звезды',
                        selectAll: 'Выбрать все',
                        unselectAll: 'Снять выбор',
                        close: 'Закрыть',
                        previous: 'Назад',
                        next: 'Вперёд',
                        navigation: 'Навигация',
                        scrollTop: 'Прокрутить вверх',
                        moveTop: 'Переместить в начало',
                        moveUp: 'Переместить вверх',
                        moveDown: 'Переместить вниз',
                        moveBottom: 'Переместить в конец',
                        moveToTarget: 'Переместить в выбранные',
                        moveToSource: 'Переместить в доступные',
                        moveAllToTarget: 'Переместить все в выбранные',
                        moveAllToSource: 'Переместить все в доступные',
                        pageLabel: 'Страница {page}',
                        firstPageLabel: 'Первая страница',
                        lastPageLabel: 'Последняя страница',
                        nextPageLabel: 'Следующая страница',
                        prevPageLabel: 'Предыдущая страница',
                        rowsPerPageLabel: 'Строк на странице',
                        jumpToPageDropdownLabel: 'Перейти к странице',
                        jumpToPageInputLabel: 'Перейти к странице',
                        selectRow: 'Выбрать строку',
                        unselectRow: 'Снять выбор строки',
                        expandRow: 'Развернуть строку',
                        collapseRow: 'Свернуть строку',
                        showFilterMenu: 'Показать фильтр',
                        hideFilterMenu: 'Скрыть фильтр',
                        filterOperator: 'Оператор фильтра',
                        filterConstraint: 'Условие фильтра',
                        editRow: 'Редактировать строку',
                        saveEdit: 'Сохранить изменения',
                        cancelEdit: 'Отменить изменения',
                        listView: 'Список',
                        gridView: 'Сетка',
                        slide: 'Слайд',
                        slideNumber: '{slideNumber}',
                        zoomImage: 'Увеличить изображение',
                        zoomIn: 'Увеличить',
                        zoomOut: 'Уменьшить',
                        rotateRight: 'Повернуть вправо',
                        rotateLeft: 'Повернуть влево',
                    },
                },
            })
            .mount(el);
    },
});
